stages:
  - build
  - package
  - deploy


.base ubuntu-18.04: &base_ubuntu_18_04
  tags: [ linux, docker ]
  image: git.imp.fu-berlin.de:5000/bioroboticslab/robofish/docker:ubuntu-18.04

.base windows: &base_windows
  tags: [ windows, docker ]
  image: git.imp.fu-berlin.de:5000/bioroboticslab/robofish/docker:windows


.build ubuntu-18.04: &build_ubuntu_18_04
  stage: build
  <<: *base_ubuntu_18_04
  variables:
    CC: gcc-8
    CXX: g++-8
  artifacts:
    paths:
      - build
    expire_in: 1 day
  before_script:
    - 'curl -o artifacts.zip --header "JOB-TOKEN: $CI_JOB_TOKEN" "https://git.imp.fu-berlin.de/api/v4/projects/2576/jobs/artifacts/master/download?job=package%20ubuntu-18.04"'
    - 7z e artifacts.zip; 7z e '*.tar.xz'; rm *.tar.xz; 7z x '*.tar'; rm *.tar
    - mkdir dependencies
    - name='RF_Interfaces'; mv $name-* dependencies/$name
    - export CMAKE_PREFIX_PATH="$(pwd)/dependencies"

.build windows: &build_windows
  stage: build
  <<: *base_windows
  artifacts:
    paths:
      - build
    expire_in: 1 day
  before_script:
    - 'curl.exe -o artifacts.zip --header "JOB-TOKEN: $CI_JOB_TOKEN" "https://git.imp.fu-berlin.de/api/v4/projects/2576/jobs/artifacts/master/download?job=package%20windows"'
    - 7z e artifacts.zip; 7z e *.tar.xz; Remove-Item -Force *.tar.xz; 7z x *.tar; Remove-Item -Force *.tar
    - New-Item -ItemType Directory -Force 'dependencies'
    - $name='RF_Interfaces'; Move-Item -Force "$name-*" dependencies/$name
    - $env:CMAKE_PREFIX_PATH="$((Get-Item -Path '.').FullName)/dependencies;$env:VCPKG_CUDA_INSTALL_DIR"
    - C:/VsDevEnv.ps1 -arch=amd64

build ubuntu-18.04:
  <<: *build_ubuntu_18_04
  script:
    - cmake -Bbuild -H. -DCMAKE_BUILD_TYPE=Release -G Ninja
    - ninja -C build

build windows:
  <<: *build_windows
  script:
    - cmake -Bbuild "-H." -DCMAKE_BUILD_TYPE=Release -G Ninja -DCMAKE_PREFIX_PATH="$Env:VCPKG_INSTALL_DIR"
    - ninja -C build

.package: &package
  stage: package
  artifacts:
    paths:
      - build/*.tar.xz
    expire_in: 1 week
  script:
    - ninja -C build package

package ubuntu-18.04:
  <<: *base_ubuntu_18_04
  dependencies:
    - build ubuntu-18.04
  before_script:
    - 'curl -o artifacts.zip --header "JOB-TOKEN: $CI_JOB_TOKEN" "https://git.imp.fu-berlin.de/api/v4/projects/2576/jobs/artifacts/master/download?job=package%20ubuntu-18.04"'
    - 7z e artifacts.zip; 7z e '*.tar.xz'; rm *.tar.xz; 7z x '*.tar'; rm *.tar
    - mkdir dependencies
    - name='RF_Interfaces'; mv $name-* dependencies/$name
    - export CMAKE_PREFIX_PATH="$(pwd)/dependencies"
  <<: *package

package windows:
  <<: *base_windows
  dependencies:
    - build windows
  before_script:
    - 'curl.exe -o artifacts.zip --header "JOB-TOKEN: $CI_JOB_TOKEN" "https://git.imp.fu-berlin.de/api/v4/projects/2576/jobs/artifacts/master/download?job=package%20windows%5bcuda%5d"'
    - 7z e artifacts.zip; 7z e *.tar.xz; Remove-Item -Force *.tar.xz; 7z x *.tar; Remove-Item -Force *.tar
    - New-Item -ItemType Directory -Force 'dependencies'
    - $name='RF_Interfaces'; Move-Item -Force "$name-*" dependencies/$name
    - $env:CMAKE_PREFIX_PATH="$((Get-Item -Path '.').FullName)/dependencies;$env:VCPKG_CUDA_INSTALL_DIR"
    - C:/VsDevEnv.ps1 -arch=amd64
  <<: *package

trigger dependents:
  stage: deploy
  <<: *base_ubuntu_18_04
  script:
    - curl --request POST --form "token=$CI_JOB_TOKEN" --form ref=master https://git.imp.fu-berlin.de/api/v4/projects/3654/trigger/pipeline
